### ISSUE TITLE
Mac端

### ISSUE THREAD

**Issue by jiongjiongJOJO** [FlatWhite233/bandizip-6.x#1]
请问从哪里下载mac端的旧版本？

**Comment by FlatWhite233** [comment]
Bandizip Mac端目前没有提供旧版本下载，请在App Store或者其他途径购买。个人比较推荐的macOS解压缩软件：Keka。

**Comment by jiongjiongJOJO** [comment]
> Bandizip Mac端目前没有提供旧版本下载，请在App Store或者其他途径购买。个人比较推荐的macOS解压缩软件：Keka。

Keka还是差点意思，Windows下用的最舒服的是7z，mac下就是bandzip
